### PR TITLE
Add About Page.

### PR DESCRIPTION
**Pull request by Akintademuyiwa24**
Add about page with its components and assets, integrate Poppins font via Google fonts and Tailwind CSS. Also updates the project dependencies

### CODE REVIEW

**Review by Richard-Raph — CHANGES_REQUESTED** [review]
1.  **You did not Update `tailwind.config.js`** to extend the theme with the custom **`font-poppins`**.
2.  **You did not Import Google Fonts and Tailwind Directives** in your CSS file.
3.  **You did not Apply the Custom Font Class** in your HTML by adding the **`font-poppins`** class to the body.
4.  **You did not Ensure Your Build Process** (i.e., Vite) is correctly set up to compile Tailwind CSS.
5.  **You did not work on your spacing between images properly.**
6.  **You shouldn't import empty components into another component (i.e., `HeroSection`)**
7.  **You did not create a route for the `AboutPage`**

**Comment by Akintademuyiwa24** [comment]
I have made the changes (routing for the about page, spacing between the images). I also merged the changes you made.

**Comment by Richard-Raph** [comment]
1.  **Align your text in the `HerSection`  to the center**
2.  **Give spaces between the rows and columns of the images in the `GallerySection`** 
3.  **Add a hover effect to the** _**See More**_ **button**

**Comment by Akintademuyiwa24** [comment]
I added the hover effect to the button and space between the images. (I just used my intuition, since there were no specifics in the design)

**Comment by Richard-Raph** [comment]
# **Good Job 👍**

  
**Your branch will be merged to the main branch after the navbar and footer have been added.**

**Pull request merged**
